services:
  web:
    image: httpd:2.4-alpine
    ports:
      - "8081:80"
    volumes:
      - .:/usr/local/apache2/htdocs
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: unless-stopped
